export const SNATCH_WORDS = [
  "love", "baby", "heart", "dance", "night", "time", "you", "me", "forever", "party",
  "fire", "rain", "home", "dream", "fly", "break", "shake", "rock", "roll", "girl",
  "boy", "money", "car", "light", "dark", "blue", "red", "sun", "moon", "star",
  "world", "life", "way", "feel", "touch", "eyes", "smile", "tears", "cry", "smile",
  "kiss", "hug", "hand", "mind", "soul", "body", "breath", "voice", "sing", "song",
  "music", "beat", "rhythm", "sound", "radio", "loud", "quiet", "fast", "slow", "high",
  "low", "good", "bad", "crazy", "wild", "sweet", "bitter", "hot", "cold", "summer",
  "winter", "spring", "fall", "rainy", "storm", "wind", "sky", "cloud", "ocean", "sea",
  "river", "mountain", "road", "street", "city", "town", "country", "world", "space", "earth",
  "name", "face", "place", "space", "time", "moment", "second", "minute", "hour", "day",
  "week", "month", "year", "yesterday", "today", "tomorrow", "tonight", "morning", "afternoon", "evening",
  "friend", "enemy", "lover", "stranger", "family", "mother", "father", "sister", "brother", "son",
  "daughter", "king", "queen", "prince", "princess", "God", "angel", "devil", "hell", "heaven",
  "true", "false", "real", "fake", "right", "wrong", "left", "right", "up", "down",
  "black", "white", "gold", "silver", "diamond", "ring", "wedding", "lonely", "alone", "together",
  "happy", "sad", "angry", "scared", "brave", "strong", "weak", "easy", "hard", "simple",
  "complex", "beautiful", "ugly", "pretty", "cute", "nice", "mean", "kind", "cruel", "magic",
  "miracle", "wonder", "secret", "truth", "lie", "promise", "regret", "hope", "wish", "luck",
  "chance", "fate", "destiny", "war", "peace", "fight", "game", "play", "win", "lose",
  "gold", "chain", "shoes", "dress", "jeans", "shirt", "hat", "glass", "bottle", "drink",
  "food", "hungry", "thirsty", "tired", "sleep", "wake", "run", "jump", "walk", "dance",
  "work", "school", "college", "boss", "job", "pay", "buy", "sell", "shop", "wait",
  "stop", "go", "start", "end", "begin", "finish", "ready", "set", "go", "fast",
  "slow", "heavy", "light", "small", "big", "large", "tiny", "huge", "tall", "short",
  "old", "new", "young", "future", "past", "present", "now", "never", "always", "sometimes",
  "maybe", "definitely", "probably", "sure", "certain", "lost", "found", "hidden", "open", "closed",
  "inside", "outside", "between", "among", "with", "without", "before", "after", "again", "once",
  "twice", "thrice", "million", "billion", "thousands", "hundreds", "zero", "one", "two", "three",
  "four", "five", "six", "seven", "eight", "nine", "ten", "easy", "harder", "better", "faster",
  "stronger", "power", "glory", "shame", "pain", "pleasure", "joy", "peace", "calm", "stormy",
  "bright", "shiny", "sparkle", "glow", "shade", "shadow", "sunlight", "moonlight", "starlight", "firelight"
];
