import { Card, Deck, DeckInfo } from "./types";

// ============================================================================
// CLASSIC DECK - The original Forbidden Flash word cards
// ============================================================================
const CLASSIC_CARDS: Card[] = [
  { id: "classic-1", word: "Elephant", forbidden: ["trunk", "big", "ears", "Africa"], points: 10, color: "yellow" },
  { id: "classic-2", word: "Pizza", forbidden: ["cheese", "circle", "Italian", "topping"], points: 10, color: "yellow" },
  { id: "classic-3", word: "Astronaut", forbidden: ["space", "moon", "NASA", "suit"], points: 20, color: "blue" },
  { id: "classic-4", word: "Guitar", forbidden: ["strings", "music", "play", "instrument"], points: 10, color: "yellow" },
  { id: "classic-5", word: "Smartphone", forbidden: ["phone", "app", "screen", "call"], points: 10, color: "yellow" },
  { id: "classic-6", word: "Library", forbidden: ["books", "quiet", "read", "building"], points: 20, color: "blue" },
  { id: "classic-7", word: "Bicycle", forbidden: ["wheels", "pedal", "ride", "helmet"], points: 10, color: "yellow" },
  { id: "classic-8", word: "Volcano", forbidden: ["lava", "hot", "mountain", "erupt"], points: 20, color: "blue" },
  { id: "classic-9", word: "Chocolate", forbidden: ["sweet", "candy", "brown", "cocoa"], points: 10, color: "yellow" },
  { id: "classic-10", word: "Butterfly", forbidden: ["wings", "insect", "caterpillar", "fly"], points: 20, color: "blue" },
  { id: "classic-11", word: "Snowman", forbidden: ["carrot", "snow", "winter", "cold"], points: 10, color: "yellow" },
  { id: "classic-12", word: "Submarine", forbidden: ["underwater", "ocean", "ship", "depth"], points: 30, color: "green" },
  { id: "classic-13", word: "Rainbow", forbidden: ["colors", "sky", "rain", "sun"], points: 20, color: "blue" },
  { id: "classic-14", word: "Kangaroo", forbidden: ["jump", "pouch", "Australia", "animal"], points: 20, color: "blue" },
  { id: "classic-15", word: "Hamburger", forbidden: ["beef", "bun", "fast food", "cheese"], points: 10, color: "yellow" },
  { id: "classic-16", word: "Parachute", forbidden: ["jump", "plane", "sky", "fall"], points: 30, color: "green" },
  { id: "classic-17", word: "Cactus", forbidden: ["desert", "spikes", "plant", "water"], points: 20, color: "blue" },
  { id: "classic-18", word: "Telescope", forbidden: ["stars", "look", "sky", "planets"], points: 30, color: "green" },
  { id: "classic-19", word: "Dinosaur", forbidden: ["extinct", "fossil", "ancient", "reptile"], points: 20, color: "blue" },
  { id: "classic-20", word: "Popcorn", forbidden: ["movie", "corn", "salt", "butter"], points: 10, color: "yellow" },
  { id: "classic-21", word: "Lighthouse", forbidden: ["ocean", "light", "ships", "coast"], points: 30, color: "green" },
  { id: "classic-22", word: "Keyboard", forbidden: ["typing", "computer", "keys", "input"], points: 10, color: "yellow" },
  { id: "classic-23", word: "Waterfall", forbidden: ["river", "water", "drop", "nature"], points: 20, color: "blue" },
  { id: "classic-24", word: "Pyramid", forbidden: ["Egypt", "triangle", "ancient", "desert"], points: 20, color: "blue" },
  { id: "classic-25", word: "Microwave", forbidden: ["heat", "kitchen", "food", "cook"], points: 10, color: "yellow" },
  { id: "classic-26", word: "Symphony", forbidden: ["orchestra", "music", "classical", "conductor"], points: 50, color: "red" },
  { id: "classic-27", word: "Backpack", forbidden: ["school", "bag", "carry", "straps"], points: 10, color: "yellow" },
  { id: "classic-28", word: "Firefighter", forbidden: ["water", "truck", "fire", "extinguish"], points: 20, color: "blue" },
  { id: "classic-29", word: "Sandwich", forbidden: ["bread", "lunch", "ham", "eat"], points: 10, color: "yellow" },
  { id: "classic-30", word: "Helicopter", forbidden: ["fly", "rotors", "pilot", "air"], points: 30, color: "green" },
  { id: "classic-31", word: "Gravity", forbidden: ["earth", "fall", "space", "force"], points: 50, color: "red" },
  { id: "classic-32", word: "Passport", forbidden: ["travel", "country", "airport", "document"], points: 30, color: "green" },
  { id: "classic-33", word: "Octopus", forbidden: ["tentacles", "sea", "eight", "ink"], points: 20, color: "blue" },
  { id: "classic-34", word: "Diamond", forbidden: ["ring", "expensive", "jewel", "hard"], points: 20, color: "blue" },
  { id: "classic-35", word: "Skeleton", forbidden: ["bones", "body", "spooky", "inside"], points: 20, color: "blue" },
  { id: "classic-36", word: "Compass", forbidden: ["north", "direction", "map", "needle"], points: 30, color: "green" },
  { id: "classic-37", word: "Bowling", forbidden: ["pins", "ball", "strike", "lane"], points: 10, color: "yellow" },
  { id: "classic-38", word: "Satellite", forbidden: ["orbit", "space", "signal", "earth"], points: 50, color: "red" },
  { id: "classic-39", word: "Tornado", forbidden: ["wind", "storm", "spin", "weather"], points: 20, color: "blue" },
  { id: "classic-40", word: "Umbrella", forbidden: ["rain", "wet", "shield", "dry"], points: 10, color: "yellow" },
  { id: "classic-41", word: "Microscope", forbidden: ["tiny", "science", "look", "cells"], points: 30, color: "green" },
  { id: "classic-42", word: "Postcard", forbidden: ["mail", "travel", "stamp", "write"], points: 20, color: "blue" },
  { id: "classic-43", word: "Rollercoaster", forbidden: ["ride", "fast", "scary", "track"], points: 20, color: "blue" },
  { id: "classic-44", word: "Philosophy", forbidden: ["thinking", "wisdom", "exist", "life"], points: 50, color: "red" },
  { id: "classic-45", word: "Scuba Diving", forbidden: ["water", "mask", "tank", "ocean"], points: 30, color: "green" },
  { id: "classic-46", word: "Chameleon", forbidden: ["color", "lizard", "change", "blend"], points: 30, color: "green" },
  { id: "classic-47", word: "Architecture", forbidden: ["building", "design", "house", "style"], points: 50, color: "red" },
  { id: "classic-48", word: "Origami", forbidden: ["paper", "fold", "Japanese", "shapes"], points: 50, color: "red" },
  { id: "classic-49", word: "Marathon", forbidden: ["run", "race", "miles", "long"], points: 30, color: "green" },
  { id: "classic-50", word: "Hibernate", forbidden: ["sleep", "winter", "bear", "animals"], points: 50, color: "red" },
  { id: "classic-51", word: "Blueprint", forbidden: ["design", "plan", "building", "engineer"], points: 50, color: "red" },
  { id: "classic-52", word: "Stethoscope", forbidden: ["doctor", "heart", "listen", "medical"], points: 30, color: "green" },
  { id: "classic-53", word: "Honey", forbidden: ["bee", "sweet", "yellow", "sticky"], points: 10, color: "yellow" },
  { id: "classic-54", word: "Penguin", forbidden: ["bird", "Antarctica", "ice", "swim"], points: 10, color: "yellow" },
  { id: "classic-55", word: "Map", forbidden: ["paper", "directions", "world", "location"], points: 10, color: "yellow" },
  { id: "classic-56", word: "Clock", forbidden: ["time", "hours", "watch", "minutes"], points: 10, color: "yellow" },
  { id: "classic-57", word: "Sun", forbidden: ["star", "hot", "sky", "yellow"], points: 10, color: "yellow" },
  { id: "classic-58", word: "Tree", forbidden: ["green", "wood", "forest", "leaves"], points: 10, color: "yellow" },
  { id: "classic-59", word: "Apple", forbidden: ["fruit", "red", "eat", "cider"], points: 10, color: "yellow" },
  { id: "classic-60", word: "Dog", forbidden: ["pet", "bark", "animal", "friend"], points: 10, color: "yellow" },
  { id: "classic-61", word: "Anchor", forbidden: ["ship", "bottom", "heavy", "ocean"], points: 20, color: "blue" },
  { id: "classic-62", word: "Bee", forbidden: ["sting", "honey", "insect", "buzz"], points: 20, color: "blue" },
  { id: "classic-63", word: "Bridge", forbidden: ["cross", "water", "road", "over"], points: 20, color: "blue" },
  { id: "classic-64", word: "Camera", forbidden: ["picture", "photo", "lens", "snap"], points: 20, color: "blue" },
  { id: "classic-65", word: "Castle", forbidden: ["king", "queen", "stone", "fort"], points: 20, color: "blue" },
  { id: "classic-66", word: "Desert", forbidden: ["sand", "hot", "dry", "camel"], points: 20, color: "blue" },
  { id: "classic-67", word: "Dragon", forbidden: ["fire", "myth", "wings", "scary"], points: 20, color: "blue" },
  { id: "classic-68", word: "Earth", forbidden: ["planet", "world", "ground", "dirt"], points: 20, color: "blue" },
  { id: "classic-69", word: "Fence", forbidden: ["yard", "gate", "wood", "enclose"], points: 20, color: "blue" },
  { id: "classic-70", word: "Glass", forbidden: ["transparent", "break", "window", "cup"], points: 20, color: "blue" },
  { id: "classic-71", word: "Hammer", forbidden: ["nail", "tool", "pound", "work"], points: 20, color: "blue" },
  { id: "classic-72", word: "Island", forbidden: ["ocean", "land", "water", "beach"], points: 20, color: "blue" },
  { id: "classic-73", word: "Jungle", forbidden: ["animals", "trees", "rain", "thick"], points: 20, color: "blue" },
  { id: "classic-74", word: "Key", forbidden: ["lock", "open", "door", "metal"], points: 20, color: "blue" },
  { id: "classic-75", word: "Lamp", forbidden: ["light", "desk", "room", "bulb"], points: 20, color: "blue" },
  { id: "classic-76", word: "Mountain", forbidden: ["climb", "high", "snow", "peak"], points: 20, color: "blue" },
  { id: "classic-77", word: "Net", forbidden: ["fish", "catch", "string", "mesh"], points: 20, color: "blue" },
  { id: "classic-78", word: "Ocean", forbidden: ["sea", "water", "blue", "salt"], points: 20, color: "blue" },
  { id: "classic-79", word: "Pillow", forbidden: ["sleep", "soft", "bed", "head"], points: 20, color: "blue" },
  { id: "classic-80", word: "Quilt", forbidden: ["blanket", "warm", "sew", "patches"], points: 20, color: "blue" },
  { id: "classic-81", word: "Rocket", forbidden: ["space", "fire", "ship", "launch"], points: 20, color: "blue" },
  { id: "classic-82", word: "Star", forbidden: ["night", "sky", "bright", "twinkle"], points: 20, color: "blue" },
  { id: "classic-83", word: "Train", forbidden: ["tracks", "station", "rail", "travel"], points: 20, color: "blue" },
  { id: "classic-84", word: "Whale", forbidden: ["big", "ocean", "swim", "water"], points: 20, color: "blue" },
  { id: "classic-85", word: "Xylophone", forbidden: ["instrument", "music", "bars", "play"], points: 20, color: "blue" },
  { id: "classic-86", word: "Yacht", forbidden: ["boat", "luxury", "water", "expensive"], points: 20, color: "blue" },
  { id: "classic-87", word: "Zebra", forbidden: ["stripes", "black", "white", "animal"], points: 20, color: "blue" },
  { id: "classic-88", word: "Alphabet", forbidden: ["letters", "ABC", "learn", "write"], points: 30, color: "green" },
  { id: "classic-89", word: "Bandage", forbidden: ["cut", "hurt", "skin", "wrap"], points: 30, color: "green" },
  { id: "classic-90", word: "Chef", forbidden: ["cook", "food", "kitchen", "restaurant"], points: 30, color: "green" },
  { id: "classic-91", word: "Doctor", forbidden: ["hospital", "sick", "medicine", "help"], points: 30, color: "green" },
  { id: "classic-92", word: "Eagle", forbidden: ["bird", "USA", "symbol", "sky"], points: 30, color: "green" },
  { id: "classic-93", word: "Forest", forbidden: ["trees", "green", "animals", "woods"], points: 30, color: "green" },
  { id: "classic-94", word: "Globe", forbidden: ["world", "round", "map", "earth"], points: 30, color: "green" },
  { id: "classic-95", word: "Harvest", forbidden: ["farm", "crops", "food", "fall"], points: 30, color: "green" },
  { id: "classic-96", word: "Incense", forbidden: ["smell", "smoke", "stick", "burn"], points: 30, color: "green" },
  { id: "classic-97", word: "Jacket", forbidden: ["wear", "cold", "coat", "zipper"], points: 30, color: "green" },
  { id: "classic-98", word: "Knight", forbidden: ["armor", "sword", "shield", "horse"], points: 30, color: "green" },
  { id: "classic-99", word: "Lumberjack", forbidden: ["trees", "ax", "cut", "wood"], points: 30, color: "green" },
  { id: "classic-100", word: "Musician", forbidden: ["instrument", "play", "band", "song"], points: 30, color: "green" },
  { id: "classic-101", word: "Newton", forbidden: ["gravity", "scientist", "apple", "physics"], points: 50, color: "red" },
  { id: "classic-102", word: "Opera", forbidden: ["sing", "loud", "music", "theater"], points: 50, color: "red" },
  { id: "classic-103", word: "Peacock", forbidden: ["feathers", "colorful", "bird", "showy"], points: 50, color: "red" },
  { id: "classic-104", word: "Quasar", forbidden: ["space", "bright", "star", "galaxy"], points: 50, color: "red" },
  { id: "classic-105", word: "Radar", forbidden: ["detect", "plane", "signal", "radio"], points: 50, color: "red" },
  { id: "classic-106", word: "Nebula", forbidden: ["space", "dust", "gas", "star"], points: 50, color: "red" },
  { id: "classic-107", word: "Galaxy", forbidden: ["stars", "space", "milky way", "big"], points: 50, color: "red" },
  { id: "classic-108", word: "Universe", forbidden: ["big", "space", "stars", "everything"], points: 50, color: "red" },
  { id: "classic-109", word: "Avalanche", forbidden: ["snow", "slide", "mountain", "dangerous"], points: 50, color: "red" },
  { id: "classic-110", word: "Metamorphosis", forbidden: ["change", "insect", "butterfly", "body"], points: 50, color: "red" },
  { id: "classic-111", word: "Paradox", forbidden: ["statement", "true", "false", "confusing"], points: 50, color: "red" },
  { id: "classic-112", word: "Quantum", forbidden: ["physics", "small", "science", "mechanics"], points: 50, color: "red" },
  { id: "classic-113", word: "Labyrinth", forbidden: ["maze", "lost", "walls", "puzzle"], points: 50, color: "red" },
  { id: "classic-114", word: "Enigma", forbidden: ["puzzle", "secret", "mystery", "hard"], points: 50, color: "red" },
  { id: "classic-115", word: "Algorithm", forbidden: ["computer", "code", "math", "steps"], points: 50, color: "red" },
];

// ============================================================================
// RANDOM RHYMES DECK - Rhyming phrase guessing game
// ============================================================================
const RANDOM_RHYMES_CARDS: Card[] = [
  // =========== EASY (Yellow, 10 pts) - Simple animal/object rhymes ===========
  { id: "rhyme-1", word: "A cat in a hat", forbidden: [], points: 10, color: "yellow", clue: "A small furry feline is wearing some stylish headwear.", answer: "A cat in a hat" },
  { id: "rhyme-2", word: "A moose drinking juice", forbidden: [], points: 10, color: "yellow", clue: "A large antlered forest mammal is sipping an orange beverage through a straw.", answer: "A moose drinking juice" },
  { id: "rhyme-3", word: "A goose on the loose", forbidden: [], points: 10, color: "yellow", clue: "A honking waterfowl has escaped and is running around freely.", answer: "A goose on the loose" },
  { id: "rhyme-4", word: "A bear in a chair", forbidden: [], points: 10, color: "yellow", clue: "A large furry woodland creature is sitting comfortably on furniture.", answer: "A bear in a chair" },
  { id: "rhyme-5", word: "A bug in a mug", forbidden: [], points: 10, color: "yellow", clue: "A tiny six-legged insect has fallen into a coffee cup.", answer: "A bug in a mug" },
  { id: "rhyme-6", word: "A snail in the mail", forbidden: [], points: 10, color: "yellow", clue: "A slow creature with a spiral shell arrived inside a postal envelope.", answer: "A snail in the mail" },
  { id: "rhyme-7", word: "A fly wearing a tie", forbidden: [], points: 10, color: "yellow", clue: "A buzzing winged insect is dressed in formal neckwear.", answer: "A fly wearing a tie" },
  { id: "rhyme-8", word: "A dog on a log", forbidden: [], points: 10, color: "yellow", clue: "A four-legged canine is sitting on a fallen tree trunk.", answer: "A dog on a log" },
  { id: "rhyme-9", word: "A fish making a wish", forbidden: [], points: 10, color: "yellow", clue: "An underwater creature with fins and scales is hoping for something special.", answer: "A fish making a wish" },
  { id: "rhyme-10", word: "A frog on a log", forbidden: [], points: 10, color: "yellow", clue: "A green jumping amphibian is resting on a fallen tree.", answer: "A frog on a log" },
  { id: "rhyme-11", word: "A bee on a knee", forbidden: [], points: 10, color: "yellow", clue: "A buzzing yellow and black striped insect is resting on someone's leg joint.", answer: "A bee on a knee" },
  { id: "rhyme-12", word: "A sheep going to sleep", forbidden: [], points: 10, color: "yellow", clue: "A woolly farm animal with fluffy white fur is getting ready for a nap.", answer: "A sheep going to sleep" },
  { id: "rhyme-13", word: "A whale eating kale", forbidden: [], points: 10, color: "yellow", clue: "A massive ocean mammal that spouts water is consuming dark leafy greens.", answer: "A whale eating kale" },
  { id: "rhyme-14", word: "A crow in the snow", forbidden: [], points: 10, color: "yellow", clue: "A black bird known for cawing is standing in frozen white precipitation.", answer: "A crow in the snow" },
  { id: "rhyme-15", word: "A snake baking a cake", forbidden: [], points: 10, color: "yellow", clue: "A slithering legless reptile is making a sweet dessert in the oven.", answer: "A snake baking a cake" },
  { id: "rhyme-16", word: "A mouse in a house", forbidden: [], points: 10, color: "yellow", clue: "A tiny gray rodent with big ears is living inside a home.", answer: "A mouse in a house" },
  { id: "rhyme-17", word: "A bat wearing a hat", forbidden: [], points: 10, color: "yellow", clue: "A night-flying winged mammal is sporting some headwear.", answer: "A bat wearing a hat" },
  { id: "rhyme-18", word: "A newt in a suit", forbidden: [], points: 10, color: "yellow", clue: "A small salamander-like creature is dressed in formal business attire.", answer: "A newt in a suit" },
  { id: "rhyme-19", word: "A pup in a cup", forbidden: [], points: 10, color: "yellow", clue: "A baby puppy is sitting inside a drinking vessel.", answer: "A pup in a cup" },
  { id: "rhyme-20", word: "A llama in pajamas", forbidden: [], points: 10, color: "yellow", clue: "A South American pack animal with a long neck is wearing comfortable sleepwear.", answer: "A llama in pajamas" },

  // =========== MEDIUM (Blue, 20 pts) - Well-known celebrities ===========
  { id: "rhyme-21", word: "Drake eating a steak", forbidden: [], points: 20, color: "blue", clue: "The Canadian 'Hotline Bling' rapper is cutting into a thick slab of grilled beef.", answer: "Drake eating a steak" },
  { id: "rhyme-22", word: "Kanye West wearing a vest", forbidden: [], points: 20, color: "blue", clue: "The Yeezy fashion designer and rapper is sporting a sleeveless jacket.", answer: "Kanye West wearing a vest" },
  { id: "rhyme-23", word: "Elon Musk wearing a tusk", forbidden: [], points: 20, color: "blue", clue: "The owner of X and Tesla is sporting a giant ivory tooth from an elephant.", answer: "Elon Musk wearing a tusk" },
  { id: "rhyme-24", word: "Danny DeVito eating a burrito", forbidden: [], points: 20, color: "blue", clue: "The star of It's Always Sunny in Philadelphia is enjoying a tin-foil-wrapped Mexican dinner.", answer: "Danny DeVito eating a burrito" },
  { id: "rhyme-25", word: "Post Malone holding a cone", forbidden: [], points: 20, color: "blue", clue: "The 'Circles' singer with face tattoos is enjoying a waffle-wrapped scoop of ice cream.", answer: "Post Malone holding a cone" },
  { id: "rhyme-26", word: "Barack Obama's in pajamas", forbidden: [], points: 20, color: "blue", clue: "The 44th President of the United States is dressed in comfortable sleepwear.", answer: "Barack Obama's in pajamas" },
  { id: "rhyme-27", word: "Tom Hanks giving thanks", forbidden: [], points: 20, color: "blue", clue: "The Forrest Gump and Cast Away star is expressing his gratitude.", answer: "Tom Hanks giving thanks" },
  { id: "rhyme-28", word: "Kevin Hart pushing a cart", forbidden: [], points: 20, color: "blue", clue: "The short comedian from Jumanji is wheeling a shopping trolley down an aisle.", answer: "Kevin Hart pushing a cart" },
  { id: "rhyme-29", word: "Brad Pitt in a pit", forbidden: [], points: 20, color: "blue", clue: "The Fight Club and Ocean's Eleven star has fallen into a hole in the ground.", answer: "Brad Pitt in a pit" },
  { id: "rhyme-30", word: "Jack Black wearing black", forbidden: [], points: 20, color: "blue", clue: "The School of Rock star is dressed entirely in dark-colored clothing.", answer: "Jack Black wearing black" },
  { id: "rhyme-31", word: "Cardi B drinking tea", forbidden: [], points: 20, color: "blue", clue: "The 'WAP' rapper from the Bronx is sipping a hot beverage from a cup.", answer: "Cardi B drinking tea" },
  { id: "rhyme-32", word: "Shaq in a sack", forbidden: [], points: 20, color: "blue", clue: "The giant basketball legend is stuck inside a large burlap bag.", answer: "Shaq in a sack" },
  { id: "rhyme-33", word: "Will Ferrell in peril", forbidden: [], points: 20, color: "blue", clue: "The Anchorman and Elf comedian is in serious danger.", answer: "Will Ferrell in peril" },
  { id: "rhyme-34", word: "LeBron James in flames", forbidden: [], points: 20, color: "blue", clue: "The Lakers basketball legend is completely surrounded by fire.", answer: "LeBron James in flames" },
  { id: "rhyme-35", word: "Beyoncé on display", forbidden: [], points: 20, color: "blue", clue: "Queen Bey is standing perfectly posed in a store window for everyone to see.", answer: "Beyoncé on display" },
  { id: "rhyme-36", word: "Billie Eilish looking stylish", forbidden: [], points: 20, color: "blue", clue: "The 'Bad Guy' singer with green hair roots appears very fashionable.", answer: "Billie Eilish looking stylish" },
  { id: "rhyme-37", word: "Miley Cyrus fighting a virus", forbidden: [], points: 20, color: "blue", clue: "The 'Wrecking Ball' singer and former Hannah Montana is battling an illness.", answer: "Miley Cyrus fighting a virus" },
  { id: "rhyme-38", word: "Adam Levine on a trampoline", forbidden: [], points: 20, color: "blue", clue: "The Maroon 5 frontman and Voice judge is bouncing on a backyard jumping apparatus.", answer: "Adam Levine on a trampoline" },
  { id: "rhyme-39", word: "Rihanna with a banana", forbidden: [], points: 20, color: "blue", clue: "The Barbados-born 'Umbrella' singer and Fenty founder is holding a yellow curved fruit.", answer: "Rihanna with a banana" },
  { id: "rhyme-40", word: "Tom Cruise on a cruise", forbidden: [], points: 20, color: "blue", clue: "The Mission Impossible star is vacationing on a large ocean liner.", answer: "Tom Cruise on a cruise" },

  // =========== HARD (Green, 30 pts) - Trickier but still known ===========
  { id: "rhyme-41", word: "Justin Bieber with a fever", forbidden: [], points: 30, color: "green", clue: "The Canadian 'Baby' and 'Sorry' singer has a high temperature and isn't feeling well.", answer: "Justin Bieber with a fever" },
  { id: "rhyme-42", word: "Stevie Nicks doing tricks", forbidden: [], points: 30, color: "green", clue: "The Fleetwood Mac singer known for 'Landslide' is performing impressive stunts.", answer: "Stevie Nicks doing tricks" },
  { id: "rhyme-43", word: "Jimmy Fallon riding a stallion", forbidden: [], points: 30, color: "green", clue: "The Tonight Show host is on the back of a male horse, galloping away.", answer: "Jimmy Fallon riding a stallion" },
  { id: "rhyme-44", word: "Bob Marley riding a Harley", forbidden: [], points: 30, color: "green", clue: "The late reggae legend who sang 'One Love' is cruising on a famous American motorcycle.", answer: "Bob Marley riding a Harley" },
  { id: "rhyme-45", word: "Bruce Lee drinking tea", forbidden: [], points: 30, color: "green", clue: "The legendary martial arts film star is calmly sipping a hot beverage.", answer: "Bruce Lee drinking tea" },
  { id: "rhyme-46", word: "Dolly Parton on a carton", forbidden: [], points: 30, color: "green", clue: "The '9 to 5' country singer with big blonde hair is standing on a milk container.", answer: "Dolly Parton on a carton" },
  { id: "rhyme-47", word: "Nicki Minaj in a garage", forbidden: [], points: 30, color: "green", clue: "The 'Super Bass' rapper with colorful wigs is standing in a place where cars are parked.", answer: "Nicki Minaj in a garage" },
  { id: "rhyme-48", word: "Eminem eating M&M's", forbidden: [], points: 30, color: "green", clue: "The Detroit rapper from 8 Mile is snacking on colorful chocolate candies.", answer: "Eminem eating M&M's" },
  { id: "rhyme-49", word: "Simon Cowell throwing in the towel", forbidden: [], points: 30, color: "green", clue: "The critical X Factor and American Idol judge is finally giving up.", answer: "Simon Cowell throwing in the towel" },
  { id: "rhyme-50", word: "Tony Hawk going for a walk", forbidden: [], points: 30, color: "green", clue: "The legendary pro skateboarder is taking a casual stroll on foot.", answer: "Tony Hawk going for a walk" },
  { id: "rhyme-51", word: "Shania Twain on a train", forbidden: [], points: 30, color: "green", clue: "The 'Man! I Feel Like a Woman!' country singer is traveling by railway.", answer: "Shania Twain on a train" },
  { id: "rhyme-52", word: "Charlie Sheen turning green", forbidden: [], points: 30, color: "green", clue: "The Two and a Half Men star is changing to a sickly color.", answer: "Charlie Sheen turning green" },
  { id: "rhyme-53", word: "Dr. Dre sipping rosé", forbidden: [], points: 30, color: "green", clue: "The Beats headphone founder and legendary producer is drinking a glass of pink wine.", answer: "Dr. Dre sipping rosé" },
  { id: "rhyme-54", word: "Ice Cube in a tube", forbidden: [], points: 30, color: "green", clue: "The 'Straight Outta Compton' rapper and Friday actor is stuck inside a cylinder.", answer: "Ice Cube in a tube" },
  { id: "rhyme-55", word: "Dave Grohl in a bowl", forbidden: [], points: 30, color: "green", clue: "The Foo Fighters frontman and former Nirvana drummer is sitting in a large dish.", answer: "Dave Grohl in a bowl" },
  { id: "rhyme-56", word: "Keanu Reeves between the leaves", forbidden: [], points: 30, color: "green", clue: "The Matrix and John Wick star is hiding among the foliage in a forest.", answer: "Keanu Reeves between the leaves" },
  { id: "rhyme-57", word: "Snoop Dogg jogging in fog", forbidden: [], points: 30, color: "green", clue: "The Long Beach rapper who loves gin and juice is running through misty weather.", answer: "Snoop Dogg jogging in fog" },
  { id: "rhyme-58", word: "Chris Rock wearing a smock", forbidden: [], points: 30, color: "green", clue: "The comedian who got slapped at the Oscars is wearing an artist's paint apron.", answer: "Chris Rock wearing a smock" },
  { id: "rhyme-59", word: "Halle Berry eating a cherry", forbidden: [], points: 30, color: "green", clue: "The Oscar-winning Catwoman actress is enjoying a small red stone fruit.", answer: "Halle Berry eating a cherry" },
  { id: "rhyme-60", word: "Jamie Foxx in a box", forbidden: [], points: 30, color: "green", clue: "The Oscar-winning Ray actor and Django star is trapped inside a cardboard container.", answer: "Jamie Foxx in a box" },

  // =========== EXPERT (Red, 50 pts) - Longer phrases or trickier ===========
  { id: "rhyme-61", word: "A gorilla eating a tortilla", forbidden: [], points: 50, color: "red", clue: "A massive great ape from the jungle is enjoying a flat, round Mexican bread.", answer: "A gorilla eating a tortilla" },
  { id: "rhyme-62", word: "Godzilla eating tortilla", forbidden: [], points: 50, color: "red", clue: "The giant Japanese movie monster that destroys cities is munching on Mexican flatbread.", answer: "Godzilla eating a tortilla" },
  { id: "rhyme-63", word: "Cinderella holding an umbrella", forbidden: [], points: 50, color: "red", clue: "The Disney princess who lost her glass slipper at midnight is carrying rain protection.", answer: "Cinderella holding an umbrella" },
  { id: "rhyme-64", word: "A chinchilla with vanilla", forbidden: [], points: 50, color: "red", clue: "A fluffy South American rodent with soft gray fur is covered in the most common ice cream flavor.", answer: "A chinchilla with vanilla" },
  { id: "rhyme-65", word: "Sylvester Stallone all alone", forbidden: [], points: 50, color: "red", clue: "The Rocky and Rambo action star is completely by himself with no one around.", answer: "Sylvester Stallone all alone" },
  { id: "rhyme-66", word: "Al Pacino at the casino", forbidden: [], points: 50, color: "red", clue: "The Scarface and Godfather actor is gambling at a gaming establishment in Las Vegas.", answer: "Al Pacino at the casino" },
  { id: "rhyme-67", word: "Robert De Niro being a hero", forbidden: [], points: 50, color: "red", clue: "The Taxi Driver and Goodfellas actor is bravely saving the day.", answer: "Robert De Niro being a hero" },
  { id: "rhyme-68", word: "Quentin Tarantino ordering a cappuccino", forbidden: [], points: 50, color: "red", clue: "The Pulp Fiction and Kill Bill director is ordering a frothy Italian espresso drink at a café.", answer: "Quentin Tarantino ordering a cappuccino" },
  { id: "rhyme-69", word: "Whoopi Goldberg eating an iceberg", forbidden: [], points: 50, color: "red", clue: "The View co-host and Sister Act star is chomping on a massive chunk of frozen glacier.", answer: "Whoopi Goldberg eating an iceberg" },
  { id: "rhyme-70", word: "Mark Zuckerberg on an iceberg", forbidden: [], points: 50, color: "red", clue: "The Facebook and Meta founder with curly hair is standing on a massive floating chunk of ice.", answer: "Mark Zuckerberg on an iceberg" },
  { id: "rhyme-71", word: "Steven Spielberg directing a berg", forbidden: [], points: 50, color: "red", clue: "The legendary Jaws and E.T. director is giving instructions to a floating chunk of ice.", answer: "Steven Spielberg directing a berg" },
  { id: "rhyme-72", word: "Danny Glover under cover", forbidden: [], points: 50, color: "red", clue: "The Lethal Weapon actor who worked with Mel Gibson is hiding beneath a blanket or disguise.", answer: "Danny Glover under cover" },
  { id: "rhyme-73", word: "Leonardo DiCaprio eating Cheerios", forbidden: [], points: 50, color: "red", clue: "The Titanic and Inception star who never caught an Oscar until The Revenant is eating round oat breakfast cereal.", answer: "Leonardo DiCaprio eating Cheerios" },
  { id: "rhyme-74", word: "Megan Thee Stallion eating a scallion", forbidden: [], points: 50, color: "red", clue: "The 'Savage' and 'WAP' rapper is biting into a green onion.", answer: "Megan Thee Stallion eating a scallion" },
  { id: "rhyme-75", word: "Doja Cat wearing a hat", forbidden: [], points: 50, color: "red", clue: "The 'Say So' and 'Kiss Me More' singer with the feline-inspired name is sporting some stylish headwear.", answer: "Doja Cat wearing a hat" },
];

// ============================================================================
// DECK REGISTRY - All available decks
// ============================================================================
export const DECK_REGISTRY: Record<string, Deck> = {
  classic: {
    info: {
      id: "classic",
      name: "Classic",
      description: "The original word collection with everyday objects, animals, and concepts",
      icon: "Zap",
      cardCount: CLASSIC_CARDS.length,
      accentColor: "#ff006e",
      deckType: "forbidden",
    },
    cards: CLASSIC_CARDS,
  },
  randomRhymes: {
    info: {
      id: "randomRhymes",
      name: "Random Rhymes",
      description: "Read the clue, guess the rhyming phrase! From 'Drake eating a steak' to 'A moose drinking juice'",
      icon: "Music",
      cardCount: RANDOM_RHYMES_CARDS.length,
      accentColor: "#8338ec",
      deckType: "rhymes",
    },
    cards: RANDOM_RHYMES_CARDS,
  },
};

// Helper functions
export function getDeck(deckId: string): Deck | undefined {
  return DECK_REGISTRY[deckId];
}

export function getAvailableDecks(): DeckInfo[] {
  return Object.values(DECK_REGISTRY).map(deck => deck.info);
}

export function getDeckCards(deckId: string): Card[] {
  const deck = DECK_REGISTRY[deckId];
  return deck ? deck.cards : CLASSIC_CARDS;
}

// Legacy export for backward compatibility
export const FORBIDDEN_CARDS = CLASSIC_CARDS;

