import { Card } from "./types";

export const FORBIDDEN_CARDS: Card[] = [
  { id: "1", word: "Elephant", forbidden: ["trunk", "big", "ears", "Africa"], points: 10, color: "yellow" },
  { id: "2", word: "Pizza", forbidden: ["cheese", "circle", "Italian", "topping"], points: 10, color: "yellow" },
  { id: "3", word: "Astronaut", forbidden: ["space", "moon", "NASA", "suit"], points: 20, color: "blue" },
  { id: "4", word: "Guitar", forbidden: ["strings", "music", "play", "instrument"], points: 10, color: "yellow" },
  { id: "5", word: "Smartphone", forbidden: ["phone", "app", "screen", "call"], points: 10, color: "yellow" },
  { id: "6", word: "Library", forbidden: ["books", "quiet", "read", "building"], points: 20, color: "blue" },
  { id: "7", word: "Bicycle", forbidden: ["wheels", "pedal", "ride", "helmet"], points: 10, color: "yellow" },
  { id: "8", word: "Volcano", forbidden: ["lava", "hot", "mountain", "erupt"], points: 20, color: "blue" },
  { id: "9", word: "Chocolate", forbidden: ["sweet", "candy", "brown", "cocoa"], points: 10, color: "yellow" },
  { id: "10", word: "Butterfly", forbidden: ["wings", "insect", "caterpillar", "fly"], points: 20, color: "blue" },
  { id: "11", word: "Snowman", forbidden: ["carrot", "snow", "winter", "cold"], points: 10, color: "yellow" },
  { id: "12", word: "Submarine", forbidden: ["underwater", "ocean", "ship", "depth"], points: 30, color: "green" },
  { id: "13", word: "Rainbow", forbidden: ["colors", "sky", "rain", "sun"], points: 20, color: "blue" },
  { id: "14", word: "Kangaroo", forbidden: ["jump", "pouch", "Australia", "animal"], points: 20, color: "blue" },
  { id: "15", word: "Hamburger", forbidden: ["beef", "bun", "fast food", "cheese"], points: 10, color: "yellow" },
  { id: "16", word: "Parachute", forbidden: ["jump", "plane", "sky", "fall"], points: 30, color: "green" },
  { id: "17", word: "Cactus", forbidden: ["desert", "spikes", "plant", "water"], points: 20, color: "blue" },
  { id: "18", word: "Telescope", forbidden: ["stars", "look", "sky", "planets"], points: 30, color: "green" },
  { id: "19", word: "Dinosaur", forbidden: ["extinct", "fossil", "ancient", "reptile"], points: 20, color: "blue" },
  { id: "20", word: "Popcorn", forbidden: ["movie", "corn", "salt", "butter"], points: 10, color: "yellow" },
  { id: "21", word: "Lighthouse", forbidden: ["ocean", "light", "ships", "coast"], points: 30, color: "green" },
  { id: "22", word: "Keyboard", forbidden: ["typing", "computer", "keys", "input"], points: 10, color: "yellow" },
  { id: "23", word: "Waterfall", forbidden: ["river", "water", "drop", "nature"], points: 20, color: "blue" },
  { id: "24", word: "Pyramid", forbidden: ["Egypt", "triangle", "ancient", "desert"], points: 20, color: "blue" },
  { id: "25", word: "Microwave", forbidden: ["heat", "kitchen", "food", "cook"], points: 10, color: "yellow" },
  { id: "26", word: "Symphony", forbidden: ["orchestra", "music", "classical", "conductor"], points: 50, color: "red" },
  { id: "27", word: "Backpack", forbidden: ["school", "bag", "carry", "straps"], points: 10, color: "yellow" },
  { id: "28", word: "Firefighter", forbidden: ["water", "truck", "fire", "extinguish"], points: 20, color: "blue" },
  { id: "29", word: "Sandwich", forbidden: ["bread", "lunch", "ham", "eat"], points: 10, color: "yellow" },
  { id: "30", word: "Helicopter", forbidden: ["fly", "rotors", "pilot", "air"], points: 30, color: "green" },
  { id: "31", word: "Gravity", forbidden: ["earth", "fall", "space", "force"], points: 50, color: "red" },
  { id: "32", word: "Passport", forbidden: ["travel", "country", "airport", "document"], points: 30, color: "green" },
  { id: "33", word: "Octopus", forbidden: ["tentacles", "sea", "eight", "ink"], points: 20, color: "blue" },
  { id: "34", word: "Diamond", forbidden: ["ring", "expensive", "jewel", "hard"], points: 20, color: "blue" },
  { id: "35", word: "Skeleton", forbidden: ["bones", "body", "spooky", "inside"], points: 20, color: "blue" },
  { id: "36", word: "Compass", forbidden: ["north", "direction", "map", "needle"], points: 30, color: "green" },
  { id: "37", word: "Bowling", forbidden: ["pins", "ball", "strike", "lane"], points: 10, color: "yellow" },
  { id: "38", word: "Satellite", forbidden: ["orbit", "space", "signal", "earth"], points: 50, color: "red" },
  { id: "39", word: "Tornado", forbidden: ["wind", "storm", "spin", "weather"], points: 20, color: "blue" },
  { id: "40", word: "Umbrella", forbidden: ["rain", "wet", "shield", "dry"], points: 10, color: "yellow" },
  { id: "41", word: "Microscope", forbidden: ["tiny", "science", "look", "cells"], points: 30, color: "green" },
  { id: "42", word: "Postcard", forbidden: ["mail", "travel", "stamp", "write"], points: 20, color: "blue" },
  { id: "43", word: "Rollercoaster", forbidden: ["ride", "fast", "scary", "track"], points: 20, color: "blue" },
  { id: "44", word: "Philosophy", forbidden: ["thinking", "wisdom", "exist", "life"], points: 50, color: "red" },
  { id: "45", word: "Scuba Diving", forbidden: ["water", "mask", "tank", "ocean"], points: 30, color: "green" },
  { id: "46", word: "Chameleon", forbidden: ["color", "lizard", "change", "blend"], points: 30, color: "green" },
  { id: "47", word: "Architecture", forbidden: ["building", "design", "house", "style"], points: 50, color: "red" },
  { id: "48", word: "Origami", forbidden: ["paper", "fold", "Japanese", "shapes"], points: 50, color: "red" },
  { id: "49", word: "Marathon", forbidden: ["run", "race", "miles", "long"], points: 30, color: "green" },
  { id: "50", word: "Hibernate", forbidden: ["sleep", "winter", "bear", "animals"], points: 50, color: "red" },
  { id: "51", word: "Blueprint", forbidden: ["design", "plan", "building", "engineer"], points: 50, color: "red" },
  { id: "52", word: "Stethoscope", forbidden: ["doctor", "heart", "listen", "medical"], points: 30, color: "green" },
];
