export interface RhymeCard {
  phrase: string;
  celeb: string;
  rhyme: string;
  difficulty: 1 | 2 | 3;
  category: 'celeb' | 'character' | 'animal' | 'object';
}

export const seedRhymes: RhymeCard[] = [
  // Celebrity Solve-It Cards (Riddle format)
  { phrase: "X-Men star with blades in his hands consuming a legume", celeb: "Wolverine", rhyme: "eating a bean", difficulty: 2, category: 'celeb' },
  { phrase: "Life Stories host and ex-Mirror editor making music in church", celeb: "Piers Morgan", rhyme: "playing the Organ", difficulty: 3, category: 'celeb' },
  { phrase: "007 actor stroking felines", celeb: "Roger Moore", rhyme: "petting cats", difficulty: 2, category: 'celeb' },
  { phrase: "Friends' paleontologist digging up bones", celeb: "Ross Geller", rhyme: "in the cellar", difficulty: 2, category: 'celeb' },
  { phrase: "Purple Rain singer causing discomfort", celeb: "Prince", rhyme: "giving a wince", difficulty: 2, category: 'celeb' },
  { phrase: "Iron Man actor with a sweet treat", celeb: "Robert Downey", rhyme: "eating a brownie", difficulty: 2, category: 'celeb' },
  { phrase: "The Matrix hero dodging projectiles", celeb: "Keanu Reeves", rhyme: "avoiding thieves", difficulty: 2, category: 'celeb' },
  { phrase: "Singer who can't stop the feeling jumping on furniture", celeb: "Justin Timberlake", rhyme: "making things shake", difficulty: 2, category: 'celeb' },
  { phrase: "Titanic actress with a precious stone", celeb: "Kate Winslet", rhyme: "wearing a bracelet", difficulty: 2, category: 'celeb' },
  { phrase: "Breaking Bad teacher cooking chemicals", celeb: "Walter White", rhyme: "in the night", difficulty: 2, category: 'celeb' },
  { phrase: "Pop star from Barbados holding an umbrella", celeb: "Rihanna", rhyme: "eating a banana", difficulty: 2, category: 'celeb' },
  { phrase: "Hunger Games heroine shooting arrows", celeb: "Katniss Everdeen", rhyme: "painted in green", difficulty: 3, category: 'celeb' },
  { phrase: "Wizard with a lightning scar getting warmer", celeb: "Harry Potter", rhyme: "getting hotter", difficulty: 1, category: 'character' },
  { phrase: "Late night talk show host jumping on a sofa", celeb: "Jimmy Fallon", rhyme: "riding a stallion", difficulty: 2, category: 'celeb' },
  { phrase: "Funny lady who voices Dory searching around", celeb: "Ellen DeGeneres", rhyme: "creating a mess", difficulty: 3, category: 'celeb' },
  { phrase: "Rapper from Toronto eating dessert", celeb: "Drake", rhyme: "having some cake", difficulty: 1, category: 'celeb' },
  { phrase: "Queen Bey in a coffee shop", celeb: "Beyonce", rhyme: "having a latte", difficulty: 2, category: 'celeb' },
  { phrase: "Spider-Man actor from England spinning webs", celeb: "Tom Holland", rhyme: "eating from a can", difficulty: 2, category: 'celeb' },
  { phrase: "Blonde pop star with a poker face doing exercise", celeb: "Lady Gaga", rhyme: "doing yoga", difficulty: 1, category: 'celeb' },
  { phrase: "Wrinkle in Time star breaking spells", celeb: "Reese Witherspoon", rhyme: "over the moon", difficulty: 2, category: 'celeb' },
  { phrase: "Rocket Man singer trimming grass", celeb: "Elton John", rhyme: "mowing the lawn", difficulty: 1, category: 'celeb' },
  { phrase: "Sherlock actor with a difficult surname scratching an itch", celeb: "Benedict Cumberbatch", rhyme: "with a scratch", difficulty: 2, category: 'celeb' },
  { phrase: "Anchorman comedian in trouble", celeb: "Will Ferrell", rhyme: "in peril", difficulty: 2, category: 'celeb' },
  { phrase: "Friends' fashion lover counting numbers", celeb: "Rachel Green", rhyme: "to nineteen", difficulty: 2, category: 'character' },
  { phrase: "Deadpool actor from Canada writing with a quill", celeb: "Ryan Reynolds", rhyme: "paying the bills", difficulty: 3, category: 'celeb' },
  
  // Original cards
  { phrase: "Kevin Spacey is lacey", celeb: "Kevin Spacey", rhyme: "lacey", difficulty: 1, category: 'celeb' },
  { phrase: "Captain Kirk at Central Perk", celeb: "Captain Kirk", rhyme: "Central Perk", difficulty: 2, category: 'character' },
  { phrase: "Megan Fox builds with blocks", celeb: "Megan Fox", rhyme: "blocks", difficulty: 1, category: 'celeb' },
  { phrase: "Ricky Gervais eats mayonnaise", celeb: "Ricky Gervais", rhyme: "mayonnaise", difficulty: 2, category: 'celeb' },
  { phrase: "David Hasselhoff has a cough", celeb: "David Hasselhoff", rhyme: "cough", difficulty: 1, category: 'celeb' },
  { phrase: "Shaggy loves Maggie", celeb: "Shaggy", rhyme: "Maggie", difficulty: 1, category: 'character' },
  { phrase: "Kanye West confesses", celeb: "Kanye West", rhyme: "confesses", difficulty: 2, category: 'celeb' },
  { phrase: "Tommy Lee Jones skipping stones", celeb: "Tommy Lee Jones", rhyme: "stones", difficulty: 2, category: 'celeb' },
  { phrase: "Simon Cowell buys a vowel", celeb: "Simon Cowell", rhyme: "vowel", difficulty: 2, category: 'celeb' },
  { phrase: "Morgan Freeman with some seamen", celeb: "Morgan Freeman", rhyme: "seamen", difficulty: 3, category: 'celeb' },
  { phrase: "Zac Efron is Teflon", celeb: "Zac Efron", rhyme: "Teflon", difficulty: 1, category: 'celeb' },
  { phrase: "Bryan Cranston in Branson", celeb: "Bryan Cranston", rhyme: "Branson", difficulty: 2, category: 'celeb' },
  { phrase: "Sean Bean being the Queen", celeb: "Sean Bean", rhyme: "Queen", difficulty: 2, category: 'celeb' },
  { phrase: "Nancy Drew says boo", celeb: "Nancy Drew", rhyme: "boo", difficulty: 1, category: 'character' },
  { phrase: "Skylar Astin is plain", celeb: "Skylar Astin", rhyme: "plain", difficulty: 2, category: 'celeb' },
  { phrase: "Roberta Flack riding a yak", celeb: "Roberta Flack", rhyme: "yak", difficulty: 2, category: 'celeb' },
  { phrase: "Dolly Parton dressed in tartan", celeb: "Dolly Parton", rhyme: "tartan", difficulty: 2, category: 'celeb' },
  { phrase: "Marilyn Monroe won't grow", celeb: "Marilyn Monroe", rhyme: "grow", difficulty: 1, category: 'celeb' },
  { phrase: "Thor is sore", celeb: "Thor", rhyme: "sore", difficulty: 1, category: 'character' },
  { phrase: "Kevin Bacon is Jamaican", celeb: "Kevin Bacon", rhyme: "Jamaican", difficulty: 1, category: 'celeb' },
  { phrase: "Benedict Cumberbatch has a scratch", celeb: "Benedict Cumberbatch", rhyme: "scratch", difficulty: 2, category: 'celeb' },
  { phrase: "Will Ferrell in peril", celeb: "Will Ferrell", rhyme: "peril", difficulty: 2, category: 'celeb' },
  { phrase: "Gwen Stefani rides Barney", celeb: "Gwen Stefani", rhyme: "Barney", difficulty: 2, category: 'celeb' },
  { phrase: "Sarah Jessica Parker likes Bob Barker", celeb: "Sarah Jessica Parker", rhyme: "Bob Barker", difficulty: 2, category: 'celeb' },
  { phrase: "Demi Moore eats boar", celeb: "Demi Moore", rhyme: "boar", difficulty: 1, category: 'celeb' },
  { phrase: "Bill Murray eats sorbet", celeb: "Bill Murray", rhyme: "sorbet", difficulty: 2, category: 'celeb' },
  { phrase: "Christian Bale sends mail", celeb: "Christian Bale", rhyme: "mail", difficulty: 1, category: 'celeb' },
  { phrase: "Fay Wray sells on eBay", celeb: "Fay Wray", rhyme: "eBay", difficulty: 2, category: 'celeb' },
  { phrase: "Piglet eating a Twiglet", celeb: "Piglet", rhyme: "Twiglet", difficulty: 2, category: 'character' },
  { phrase: "Tom Cruise in platform shoes", celeb: "Tom Cruise", rhyme: "shoes", difficulty: 1, category: 'celeb' },
  { phrase: "The Yeti eating spaghetti", celeb: "The Yeti", rhyme: "spaghetti", difficulty: 1, category: 'character' },
  { phrase: "Stevie Wonder's scared of thunder", celeb: "Stevie Wonder", rhyme: "thunder", difficulty: 2, category: 'celeb' },
  { phrase: "Brad Pitt with Banana Split", celeb: "Brad Pitt", rhyme: "Banana Split", difficulty: 2, category: 'celeb' },
  { phrase: "Killer whale loves kale", celeb: "Killer whale", rhyme: "kale", difficulty: 1, category: 'animal' },
];

export const generatedRhymes: RhymeCard[] = [
  { phrase: "Lady Gaga does yoga", celeb: "Lady Gaga", rhyme: "yoga", difficulty: 1, category: 'celeb' },
  { phrase: "Justin Bieber has a fever", celeb: "Justin Bieber", rhyme: "fever", difficulty: 1, category: 'celeb' },
  { phrase: "Taylor Swift lifting weights", celeb: "Taylor Swift", rhyme: "weights", difficulty: 2, category: 'celeb' },
  { phrase: "Drake eating cake", celeb: "Drake", rhyme: "cake", difficulty: 1, category: 'celeb' },
  { phrase: "Beyonce in a cafe", celeb: "Beyonce", rhyme: "cafe", difficulty: 2, category: 'celeb' },
  { phrase: "Oprah Winfrey wins the lottery", celeb: "Oprah Winfrey", rhyme: "lottery", difficulty: 2, category: 'celeb' },
  { phrase: "Johnny Depp takes a step", celeb: "Johnny Depp", rhyme: "step", difficulty: 1, category: 'celeb' },
  { phrase: "Angelina Jolie is holy", celeb: "Angelina Jolie", rhyme: "holy", difficulty: 2, category: 'celeb' },
  { phrase: "Leonardo DiCaprio eating Cheerios", celeb: "Leonardo DiCaprio", rhyme: "Cheerios", difficulty: 2, category: 'celeb' },
  { phrase: "Jennifer Lawrence wearing orange", celeb: "Jennifer Lawrence", rhyme: "orange", difficulty: 3, category: 'celeb' },
  { phrase: "Ryan Gosling bowling", celeb: "Ryan Gosling", rhyme: "bowling", difficulty: 2, category: 'celeb' },
  { phrase: "Emma Stone on the phone", celeb: "Emma Stone", rhyme: "phone", difficulty: 1, category: 'celeb' },
  { phrase: "Chris Hemsworth going north", celeb: "Chris Hemsworth", rhyme: "north", difficulty: 2, category: 'celeb' },
  { phrase: "Scarlett Johansson wearing pajamas on", celeb: "Scarlett Johansson", rhyme: "pajamas", difficulty: 2, category: 'celeb' },
  { phrase: "Tom Hanks in a tank", celeb: "Tom Hanks", rhyme: "tank", difficulty: 1, category: 'celeb' },
  { phrase: "Meryl Streep counting sheep", celeb: "Meryl Streep", rhyme: "sheep", difficulty: 1, category: 'celeb' },
  { phrase: "Robert Downey junior eating honey", celeb: "Robert Downey Jr", rhyme: "honey", difficulty: 2, category: 'celeb' },
  { phrase: "Keanu Reeves raking leaves", celeb: "Keanu Reeves", rhyme: "leaves", difficulty: 1, category: 'celeb' },
  { phrase: "Samuel Jackson snacking", celeb: "Samuel Jackson", rhyme: "snacking", difficulty: 2, category: 'celeb' },
  { phrase: "Dwayne The Rock Johnson wearing socks on", celeb: "Dwayne Johnson", rhyme: "socks", difficulty: 1, category: 'celeb' },
  { phrase: "Harry Styles eating piles", celeb: "Harry Styles", rhyme: "piles", difficulty: 2, category: 'celeb' },
  { phrase: "Ariana Grande at the candy stand", celeb: "Ariana Grande", rhyme: "stand", difficulty: 2, category: 'celeb' },
  { phrase: "Elton John mowing the lawn", celeb: "Elton John", rhyme: "lawn", difficulty: 1, category: 'celeb' },
  { phrase: "Miley Cyrus on a virus", celeb: "Miley Cyrus", rhyme: "virus", difficulty: 2, category: 'celeb' },
  { phrase: "Katy Perry eating a cherry", celeb: "Katy Perry", rhyme: "cherry", difficulty: 1, category: 'celeb' },
  { phrase: "Ed Sheeran steering", celeb: "Ed Sheeran", rhyme: "steering", difficulty: 2, category: 'celeb' },
  { phrase: "Adele with a bell", celeb: "Adele", rhyme: "bell", difficulty: 1, category: 'celeb' },
  { phrase: "Post Malone eating scones", celeb: "Post Malone", rhyme: "scones", difficulty: 2, category: 'celeb' },
  { phrase: "Billie Eilish being stylish", celeb: "Billie Eilish", rhyme: "stylish", difficulty: 2, category: 'celeb' },
  { phrase: "Cardi B drinking tea", celeb: "Cardi B", rhyme: "tea", difficulty: 1, category: 'celeb' },
  { phrase: "Lizzo eating pizza", celeb: "Lizzo", rhyme: "pizza", difficulty: 1, category: 'celeb' },
  { phrase: "The Weeknd getting weakened", celeb: "The Weeknd", rhyme: "weakened", difficulty: 2, category: 'celeb' },
  { phrase: "Shawn Mendes playing tennis", celeb: "Shawn Mendes", rhyme: "tennis", difficulty: 2, category: 'celeb' },
  { phrase: "Selena Gomez on a boat", celeb: "Selena Gomez", rhyme: "boat", difficulty: 2, category: 'celeb' },
  { phrase: "Dua Lipa eating pizza", celeb: "Dua Lipa", rhyme: "pizza", difficulty: 1, category: 'celeb' },
  { phrase: "Harry Potter gets hotter", celeb: "Harry Potter", rhyme: "hotter", difficulty: 1, category: 'character' },
  { phrase: "Hermione Granger in danger", celeb: "Hermione Granger", rhyme: "danger", difficulty: 2, category: 'character' },
  { phrase: "Ron Weasley feeling queasy", celeb: "Ron Weasley", rhyme: "queasy", difficulty: 2, category: 'character' },
  { phrase: "Darth Vader eating a potato", celeb: "Darth Vader", rhyme: "potato", difficulty: 2, category: 'character' },
  { phrase: "Luke Skywalker is a stalker", celeb: "Luke Skywalker", rhyme: "stalker", difficulty: 2, category: 'character' },
  { phrase: "Princess Leia plays Yahtzee", celeb: "Princess Leia", rhyme: "Yahtzee", difficulty: 3, category: 'character' },
  { phrase: "Yoda doing yoga", celeb: "Yoda", rhyme: "yoga", difficulty: 1, category: 'character' },
  { phrase: "Gandalf takes a bath", celeb: "Gandalf", rhyme: "bath", difficulty: 1, category: 'character' },
  { phrase: "Frodo eating a burrito", celeb: "Frodo", rhyme: "burrito", difficulty: 2, category: 'character' },
  { phrase: "Gollum at the bottom", celeb: "Gollum", rhyme: "bottom", difficulty: 2, category: 'character' },
  { phrase: "Batman eating rattan", celeb: "Batman", rhyme: "rattan", difficulty: 2, category: 'character' },
  { phrase: "Superman on a pan", celeb: "Superman", rhyme: "pan", difficulty: 1, category: 'character' },
  { phrase: "Wonder Woman doing yoga", celeb: "Wonder Woman", rhyme: "yoga", difficulty: 2, category: 'character' },
  { phrase: "Spider-Man eating fried ham", celeb: "Spider-Man", rhyme: "ham", difficulty: 1, category: 'character' },
  { phrase: "Iron Man with a frying pan", celeb: "Iron Man", rhyme: "pan", difficulty: 1, category: 'character' },
  { phrase: "Hulk drinking milk", celeb: "Hulk", rhyme: "milk", difficulty: 1, category: 'character' },
  { phrase: "Black Widow on a meadow", celeb: "Black Widow", rhyme: "meadow", difficulty: 2, category: 'character' },
  { phrase: "Captain America in a cafeteria", celeb: "Captain America", rhyme: "cafeteria", difficulty: 2, category: 'character' },
  { phrase: "Elsa freezing pizza", celeb: "Elsa", rhyme: "pizza", difficulty: 1, category: 'character' },
  { phrase: "Anna with a banana", celeb: "Anna", rhyme: "banana", difficulty: 1, category: 'character' },
  { phrase: "Olaf taking a bath", celeb: "Olaf", rhyme: "bath", difficulty: 1, category: 'character' },
  { phrase: "Simba on Roomba", celeb: "Simba", rhyme: "Roomba", difficulty: 2, category: 'character' },
  { phrase: "Nemo eating Oreos", celeb: "Nemo", rhyme: "Oreos", difficulty: 2, category: 'character' },
  { phrase: "Dory telling a story", celeb: "Dory", rhyme: "story", difficulty: 1, category: 'character' },
  { phrase: "Woody feeling moody", celeb: "Woody", rhyme: "moody", difficulty: 1, category: 'character' },
  { phrase: "Buzz Lightyear drinking beer", celeb: "Buzz Lightyear", rhyme: "beer", difficulty: 2, category: 'character' },
  { phrase: "Shrek on the deck", celeb: "Shrek", rhyme: "deck", difficulty: 1, category: 'character' },
  { phrase: "Donkey being funky", celeb: "Donkey", rhyme: "funky", difficulty: 1, category: 'character' },
  { phrase: "Spongebob eating corn on the cob", celeb: "Spongebob", rhyme: "cob", difficulty: 1, category: 'character' },
  { phrase: "Patrick on a hat trick", celeb: "Patrick", rhyme: "hat trick", difficulty: 2, category: 'character' },
  { phrase: "Mickey Mouse in a house", celeb: "Mickey Mouse", rhyme: "house", difficulty: 1, category: 'character' },
  { phrase: "Donald Duck driving a truck", celeb: "Donald Duck", rhyme: "truck", difficulty: 1, category: 'character' },
  { phrase: "Winnie the Pooh eating fondue", celeb: "Winnie the Pooh", rhyme: "fondue", difficulty: 2, category: 'character' },
  { phrase: "Bugs Bunny counting money", celeb: "Bugs Bunny", rhyme: "money", difficulty: 1, category: 'character' },
  { phrase: "Pikachu wearing a shoe", celeb: "Pikachu", rhyme: "shoe", difficulty: 1, category: 'character' },
  { phrase: "Mario eating Oreos", celeb: "Mario", rhyme: "Oreos", difficulty: 1, category: 'character' },
  { phrase: "Luigi playing squeegee", celeb: "Luigi", rhyme: "squeegee", difficulty: 2, category: 'character' },
  { phrase: "Sonic being chronic", celeb: "Sonic", rhyme: "chronic", difficulty: 2, category: 'character' },
  { phrase: "Pac-Man eating ham", celeb: "Pac-Man", rhyme: "ham", difficulty: 1, category: 'character' },
  { phrase: "Link in a sink", celeb: "Link", rhyme: "sink", difficulty: 1, category: 'character' },
  { phrase: "Zelda with an umbrella", celeb: "Zelda", rhyme: "umbrella", difficulty: 2, category: 'character' },
  { phrase: "Giraffe taking a bath", celeb: "Giraffe", rhyme: "bath", difficulty: 1, category: 'animal' },
  { phrase: "Penguin juggling", celeb: "Penguin", rhyme: "juggling", difficulty: 2, category: 'animal' },
  { phrase: "Elephant wearing velvet", celeb: "Elephant", rhyme: "velvet", difficulty: 2, category: 'animal' },
  { phrase: "Kangaroo in a canoe", celeb: "Kangaroo", rhyme: "canoe", difficulty: 1, category: 'animal' },
  { phrase: "Zebra eating Debra", celeb: "Zebra", rhyme: "Debra", difficulty: 2, category: 'animal' },
  { phrase: "Hippo playing limbo", celeb: "Hippo", rhyme: "limbo", difficulty: 1, category: 'animal' },
  { phrase: "Sloth making broth", celeb: "Sloth", rhyme: "broth", difficulty: 1, category: 'animal' },
  { phrase: "Dolphin golfing", celeb: "Dolphin", rhyme: "golfing", difficulty: 2, category: 'animal' },
  { phrase: "Octopus on a bus", celeb: "Octopus", rhyme: "bus", difficulty: 1, category: 'animal' },
  { phrase: "Parrot eating a carrot", celeb: "Parrot", rhyme: "carrot", difficulty: 1, category: 'animal' },
  { phrase: "Flamingo playing bingo", celeb: "Flamingo", rhyme: "bingo", difficulty: 1, category: 'animal' },
  { phrase: "Cheetah eating pizza", celeb: "Cheetah", rhyme: "pizza", difficulty: 1, category: 'animal' },
  { phrase: "Panda eating Amanda", celeb: "Panda", rhyme: "Amanda", difficulty: 2, category: 'animal' },
  { phrase: "Koala wearing Prada", celeb: "Koala", rhyme: "Prada", difficulty: 2, category: 'animal' },
  { phrase: "Llama in pajamas", celeb: "Llama", rhyme: "pajamas", difficulty: 1, category: 'animal' },
  { phrase: "Tiger in a diaper", celeb: "Tiger", rhyme: "diaper", difficulty: 2, category: 'animal' },
  { phrase: "Lion buying an iron", celeb: "Lion", rhyme: "iron", difficulty: 2, category: 'animal' },
  { phrase: "Bear combing hair", celeb: "Bear", rhyme: "hair", difficulty: 1, category: 'animal' },
  { phrase: "Moose drinking juice", celeb: "Moose", rhyme: "juice", difficulty: 1, category: 'animal' },
  { phrase: "Raccoon eating macaroons", celeb: "Raccoon", rhyme: "macaroons", difficulty: 2, category: 'animal' },
  { phrase: "Squirrel doing a twirl", celeb: "Squirrel", rhyme: "twirl", difficulty: 1, category: 'animal' },
  { phrase: "Shark in the park", celeb: "Shark", rhyme: "park", difficulty: 1, category: 'animal' },
  { phrase: "Snake eating cake", celeb: "Snake", rhyme: "cake", difficulty: 1, category: 'animal' },
  { phrase: "Turtle wearing purple", celeb: "Turtle", rhyme: "purple", difficulty: 1, category: 'animal' },
  { phrase: "Frog on a log", celeb: "Frog", rhyme: "log", difficulty: 1, category: 'animal' },
  { phrase: "Owl with a towel", celeb: "Owl", rhyme: "towel", difficulty: 1, category: 'animal' },
  { phrase: "Eagle eating a bagel", celeb: "Eagle", rhyme: "bagel", difficulty: 1, category: 'animal' },
  { phrase: "Bat with a hat", celeb: "Bat", rhyme: "hat", difficulty: 1, category: 'animal' },
  { phrase: "Monkey getting funky", celeb: "Monkey", rhyme: "funky", difficulty: 1, category: 'animal' },
  { phrase: "Gorilla eating vanilla", celeb: "Gorilla", rhyme: "vanilla", difficulty: 1, category: 'animal' },
  { phrase: "Walrus with a chorus", celeb: "Walrus", rhyme: "chorus", difficulty: 2, category: 'animal' },
  { phrase: "Seal making a deal", celeb: "Seal", rhyme: "deal", difficulty: 1, category: 'animal' },
  { phrase: "Beaver with a cleaver", celeb: "Beaver", rhyme: "cleaver", difficulty: 2, category: 'animal' },
  { phrase: "Otter getting hotter", celeb: "Otter", rhyme: "hotter", difficulty: 1, category: 'animal' },
  { phrase: "Hedgehog on a sledge", celeb: "Hedgehog", rhyme: "sledge", difficulty: 2, category: 'animal' },
  { phrase: "Rabbit in a habit", celeb: "Rabbit", rhyme: "habit", difficulty: 2, category: 'animal' },
  { phrase: "Hamster being a gangster", celeb: "Hamster", rhyme: "gangster", difficulty: 2, category: 'animal' },
  { phrase: "Chipmunk in a trunk", celeb: "Chipmunk", rhyme: "trunk", difficulty: 1, category: 'animal' },
  { phrase: "Rhino drinking vino", celeb: "Rhino", rhyme: "vino", difficulty: 2, category: 'animal' },
  { phrase: "Camel with a camera", celeb: "Camel", rhyme: "camera", difficulty: 2, category: 'animal' },
  { phrase: "Peacock on a rock", celeb: "Peacock", rhyme: "rock", difficulty: 1, category: 'animal' },
  { phrase: "Crow eating dough", celeb: "Crow", rhyme: "dough", difficulty: 1, category: 'animal' },
  { phrase: "Duck driving a truck", celeb: "Duck", rhyme: "truck", difficulty: 1, category: 'animal' },
  { phrase: "Goose getting loose", celeb: "Goose", rhyme: "loose", difficulty: 1, category: 'animal' },
  { phrase: "Swan with pom poms on", celeb: "Swan", rhyme: "pom poms", difficulty: 2, category: 'animal' },
  { phrase: "Chicken picking", celeb: "Chicken", rhyme: "picking", difficulty: 1, category: 'animal' },
  { phrase: "Turkey being quirky", celeb: "Turkey", rhyme: "quirky", difficulty: 1, category: 'animal' },
  { phrase: "Horse playing golf course", celeb: "Horse", rhyme: "golf course", difficulty: 2, category: 'animal' },
  { phrase: "Donkey looking funky", celeb: "Donkey", rhyme: "funky", difficulty: 1, category: 'animal' },
  { phrase: "Pig wearing a wig", celeb: "Pig", rhyme: "wig", difficulty: 1, category: 'animal' },
  { phrase: "Cow saying wow", celeb: "Cow", rhyme: "wow", difficulty: 1, category: 'animal' },
  { phrase: "Sheep counting deep", celeb: "Sheep", rhyme: "deep", difficulty: 1, category: 'animal' },
  { phrase: "Goat wearing a coat", celeb: "Goat", rhyme: "coat", difficulty: 1, category: 'animal' },
  { phrase: "Dog on a log", celeb: "Dog", rhyme: "log", difficulty: 1, category: 'animal' },
  { phrase: "Cat wearing a hat", celeb: "Cat", rhyme: "hat", difficulty: 1, category: 'animal' },
  { phrase: "Mouse in a house", celeb: "Mouse", rhyme: "house", difficulty: 1, category: 'animal' },
  { phrase: "Rat being fat", celeb: "Rat", rhyme: "fat", difficulty: 1, category: 'animal' },
  { phrase: "Fish with a dish", celeb: "Fish", rhyme: "dish", difficulty: 1, category: 'animal' },
  { phrase: "Goldfish making a wish", celeb: "Goldfish", rhyme: "wish", difficulty: 1, category: 'animal' },
  { phrase: "Butterfly eating pie", celeb: "Butterfly", rhyme: "pie", difficulty: 1, category: 'animal' },
  { phrase: "Bee drinking tea", celeb: "Bee", rhyme: "tea", difficulty: 1, category: 'animal' },
  { phrase: "Spider on a glider", celeb: "Spider", rhyme: "glider", difficulty: 2, category: 'animal' },
  { phrase: "Ant wearing pants", celeb: "Ant", rhyme: "pants", difficulty: 1, category: 'animal' },
  { phrase: "Ladybug on a rug", celeb: "Ladybug", rhyme: "rug", difficulty: 1, category: 'animal' },
  { phrase: "Caterpillar being a killer", celeb: "Caterpillar", rhyme: "killer", difficulty: 2, category: 'animal' },
  { phrase: "Worm doing homework", celeb: "Worm", rhyme: "homework", difficulty: 2, category: 'animal' },
  { phrase: "Snail getting mail", celeb: "Snail", rhyme: "mail", difficulty: 1, category: 'animal' },
  { phrase: "Crab being fab", celeb: "Crab", rhyme: "fab", difficulty: 1, category: 'animal' },
  { phrase: "Lobster being a mobster", celeb: "Lobster", rhyme: "mobster", difficulty: 2, category: 'animal' },
  { phrase: "Jellyfish eating fish", celeb: "Jellyfish", rhyme: "fish", difficulty: 1, category: 'animal' },
  { phrase: "Starfish making a wish", celeb: "Starfish", rhyme: "wish", difficulty: 1, category: 'animal' },
  { phrase: "Seahorse on a golf course", celeb: "Seahorse", rhyme: "golf course", difficulty: 2, category: 'animal' },
  { phrase: "Dinosaur being a bore", celeb: "Dinosaur", rhyme: "bore", difficulty: 1, category: 'animal' },
  { phrase: "T-Rex wearing specs", celeb: "T-Rex", rhyme: "specs", difficulty: 1, category: 'animal' },
  { phrase: "Triceratops eating pork chops", celeb: "Triceratops", rhyme: "pork chops", difficulty: 2, category: 'animal' },
  { phrase: "Dragon on a wagon", celeb: "Dragon", rhyme: "wagon", difficulty: 1, category: 'character' },
  { phrase: "Unicorn eating corn", celeb: "Unicorn", rhyme: "corn", difficulty: 1, category: 'character' },
  { phrase: "Phoenix eating Wheaties", celeb: "Phoenix", rhyme: "Wheaties", difficulty: 2, category: 'character' },
  { phrase: "Mermaid getting paid", celeb: "Mermaid", rhyme: "paid", difficulty: 1, category: 'character' },
  { phrase: "Vampire with a fire", celeb: "Vampire", rhyme: "fire", difficulty: 1, category: 'character' },
  { phrase: "Zombie eating hummus", celeb: "Zombie", rhyme: "hummus", difficulty: 2, category: 'character' },
  { phrase: "Werewolf on the roof", celeb: "Werewolf", rhyme: "roof", difficulty: 1, category: 'character' },
  { phrase: "Ghost eating toast", celeb: "Ghost", rhyme: "toast", difficulty: 1, category: 'character' },
  { phrase: "Witch with a switch", celeb: "Witch", rhyme: "switch", difficulty: 1, category: 'character' },
  { phrase: "Wizard is a blizzard", celeb: "Wizard", rhyme: "blizzard", difficulty: 2, category: 'character' },
  { phrase: "Fairy eating berry", celeb: "Fairy", rhyme: "berry", difficulty: 1, category: 'character' },
  { phrase: "Goblin juggling", celeb: "Goblin", rhyme: "juggling", difficulty: 2, category: 'character' },
  { phrase: "Troll on a roll", celeb: "Troll", rhyme: "roll", difficulty: 1, category: 'character' },
  { phrase: "Ogre playing poker", celeb: "Ogre", rhyme: "poker", difficulty: 2, category: 'character' },
  { phrase: "Elf on a shelf", celeb: "Elf", rhyme: "shelf", difficulty: 1, category: 'character' },
  { phrase: "Santa eating a banana", celeb: "Santa", rhyme: "banana", difficulty: 1, category: 'character' },
  { phrase: "Rudolph playing golf", celeb: "Rudolph", rhyme: "golf", difficulty: 1, category: 'character' },
  { phrase: "Easter Bunny counting money", celeb: "Easter Bunny", rhyme: "money", difficulty: 1, category: 'character' },
  { phrase: "Tooth Fairy drinking dairy", celeb: "Tooth Fairy", rhyme: "dairy", difficulty: 2, category: 'character' },
  { phrase: "Cupid being stupid", celeb: "Cupid", rhyme: "stupid", difficulty: 1, category: 'character' },
  { phrase: "Grim Reaper being cheaper", celeb: "Grim Reaper", rhyme: "cheaper", difficulty: 2, category: 'character' },
  { phrase: "Alien playing violin", celeb: "Alien", rhyme: "violin", difficulty: 2, category: 'character' },
  { phrase: "Robot eating carrots", celeb: "Robot", rhyme: "carrots", difficulty: 2, category: 'object' },
  { phrase: "Pirate on a diet", celeb: "Pirate", rhyme: "diet", difficulty: 1, category: 'character' },
  { phrase: "Ninja eating cheese and spinach", celeb: "Ninja", rhyme: "spinach", difficulty: 2, category: 'character' },
  { phrase: "Cowboy being a toy", celeb: "Cowboy", rhyme: "toy", difficulty: 1, category: 'character' },
  { phrase: "Astronaut eating tots", celeb: "Astronaut", rhyme: "tots", difficulty: 2, category: 'character' },
];

export const allRhymes: RhymeCard[] = [...seedRhymes, ...generatedRhymes];

export function shuffleDeck(deck: RhymeCard[] = allRhymes): RhymeCard[] {
  const shuffled = [...deck];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getDeckByDifficulty(difficulty: 1 | 2 | 3): RhymeCard[] {
  return allRhymes.filter(card => card.difficulty === difficulty);
}

export function getDeckByCategory(category: RhymeCard['category']): RhymeCard[] {
  return allRhymes.filter(card => card.category === category);
}