import { CAPITALS_QUESTIONS, FLAGS_QUESTIONS, COUNTRIES_QUESTIONS, LANGUAGES_QUESTIONS } from "./geography";
import { DATES_QUESTIONS, FAMOUS_FIGURES_QUESTIONS, EVENTS_QUESTIONS, LOCATIONS_QUESTIONS } from "./history";
import { ATHLETES_QUESTIONS, TEAMS_QUESTIONS, SPORTS_TERMS_QUESTIONS, SPORTS_EVENTS_QUESTIONS } from "./sports";
import { ARTISTS_QUESTIONS, LYRICS_QUESTIONS, AWARDS_QUESTIONS, TITLES_QUESTIONS } from "./music";
import { BIOLOGY_QUESTIONS, PHYSICS_QUESTIONS, ASTRONOMY_QUESTIONS, CHEMISTRY_QUESTIONS } from "./science";
import { MOVIES_QUESTIONS, TV_SHOWS_QUESTIONS, GAMING_QUESTIONS, POP_ICONS_QUESTIONS } from "./entertainment";

export const ALL_MODULAR_QUESTIONS = [
    ...CAPITALS_QUESTIONS,
    ...FLAGS_QUESTIONS,
    ...COUNTRIES_QUESTIONS,
    ...LANGUAGES_QUESTIONS,
    ...DATES_QUESTIONS,
    ...FAMOUS_FIGURES_QUESTIONS,
    ...EVENTS_QUESTIONS,
    ...LOCATIONS_QUESTIONS,
    ...ATHLETES_QUESTIONS,
    ...TEAMS_QUESTIONS,
    ...SPORTS_TERMS_QUESTIONS,
    ...SPORTS_EVENTS_QUESTIONS,
    ...ARTISTS_QUESTIONS,
    ...LYRICS_QUESTIONS,
    ...AWARDS_QUESTIONS,
    ...TITLES_QUESTIONS,
    ...BIOLOGY_QUESTIONS,
    ...PHYSICS_QUESTIONS,
    ...ASTRONOMY_QUESTIONS,
    ...CHEMISTRY_QUESTIONS,
    ...MOVIES_QUESTIONS,
    ...TV_SHOWS_QUESTIONS,
    ...GAMING_QUESTIONS,
    ...POP_ICONS_QUESTIONS
];
